/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author 23065
 */
public class ScrimCalculator extends javax.swing.JFrame {
    
    double firstNumber;
    double secondNumber;
    double result;
    String operation;
    double memoryReturn;
    /**
     * Creates new form ScrimCalculator
     */
    public ScrimCalculator() {
        initComponents();
        List<JButton> botoes = pegaBotoes(getContentPane());
        for (JButton botao : botoes){
            botao.setFont(new Font( "Arial" , Font.PLAIN,30 ));
        }
    displayScreen.setFont(new Font("Arial", Font.PLAIN,30 ));
    }
    
    public List<JButton> pegaBotoes(Container container){
        List<JButton> botoes = new ArrayList<>();
        Component[] componentes = container.getComponents();
        
        for(Component componente : componentes){
            if (componente instanceof JButton){
            botoes.add((JButton) componente);
        }
        }
        return botoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayScreen = new javax.swing.JTextField();
        buttonMemoryless = new javax.swing.JButton();
        buttonMemoryReturn = new javax.swing.JButton();
        buttonMemoryClear = new javax.swing.JButton();
        buttonMemoryMore = new javax.swing.JButton();
        buttonMoreOrLess = new javax.swing.JButton();
        buttonDivision = new javax.swing.JButton();
        buttonMulti = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonLess = new javax.swing.JButton();
        buttonSum = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        botãoZero = new javax.swing.JButton();
        buttomPoint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        displayScreen.setBackground(new java.awt.Color(0, 0, 0));
        displayScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonMemoryless.setBackground(new java.awt.Color(204, 204, 204));
        buttonMemoryless.setForeground(new java.awt.Color(0, 0, 0));
        buttonMemoryless.setText("M/-");
        buttonMemoryless.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonMemoryless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemorylessActionPerformed(evt);
            }
        });

        buttonMemoryReturn.setBackground(new java.awt.Color(255, 153, 0));
        buttonMemoryReturn.setText("M/R");
        buttonMemoryReturn.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonMemoryReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryReturnActionPerformed(evt);
            }
        });

        buttonMemoryClear.setBackground(new java.awt.Color(204, 204, 204));
        buttonMemoryClear.setForeground(new java.awt.Color(0, 0, 0));
        buttonMemoryClear.setText("M/C");
        buttonMemoryClear.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryClearActionPerformed(evt);
            }
        });

        buttonMemoryMore.setBackground(new java.awt.Color(204, 204, 204));
        buttonMemoryMore.setForeground(new java.awt.Color(0, 0, 0));
        buttonMemoryMore.setText("M/+");
        buttonMemoryMore.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonMemoryMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryMoreActionPerformed(evt);
            }
        });

        buttonMoreOrLess.setText("+/-");
        buttonMoreOrLess.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonMoreOrLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMoreOrLessActionPerformed(evt);
            }
        });

        buttonDivision.setText("/");
        buttonDivision.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivisionActionPerformed(evt);
            }
        });

        buttonMulti.setBackground(new java.awt.Color(255, 153, 0));
        buttonMulti.setText("X");
        buttonMulti.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiActionPerformed(evt);
            }
        });

        buttonClear.setText("C");
        buttonClear.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonSeven.setText("7");
        buttonSeven.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonEight.setText("8");
        buttonEight.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonNine.setText("9");
        buttonNine.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });

        buttonLess.setBackground(new java.awt.Color(255, 153, 0));
        buttonLess.setText("-");
        buttonLess.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLessActionPerformed(evt);
            }
        });

        buttonSum.setBackground(new java.awt.Color(255, 153, 0));
        buttonSum.setText("+");
        buttonSum.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumActionPerformed(evt);
            }
        });

        buttonFive.setText("5");
        buttonFive.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonSix.setText("6");
        buttonSix.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonFour.setText("4");
        buttonFour.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonTwo.setText("2");
        buttonTwo.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonThree.setText("3");
        buttonThree.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });

        buttonOne.setText("1");
        buttonOne.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonEquals.setBackground(new java.awt.Color(255, 153, 0));
        buttonEquals.setText("=");
        buttonEquals.setMaximumSize(new java.awt.Dimension(110, 70));
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        botãoZero.setText("0");
        botãoZero.setMaximumSize(new java.awt.Dimension(110, 70));
        botãoZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoZeroActionPerformed(evt);
            }
        });

        buttomPoint.setText(".");
        buttomPoint.setMaximumSize(new java.awt.Dimension(110, 70));
        buttomPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomPointActionPerformed(evt);
            }
        });

        jLabel1.setText("Produzido por abacaxi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayScreen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMemoryMore, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMemoryless, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonMemoryReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMoreOrLess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(buttonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(buttonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botãoZero, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttomPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMemoryReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMemoryMore, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMemoryless, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMoreOrLess, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttomPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botãoZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonEquals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMemorylessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemorylessActionPerformed
        
    }//GEN-LAST:event_buttonMemorylessActionPerformed

    private void buttonMemoryReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryReturnActionPerformed
        
            
            
            displayScreen.setText(""+memoryReturn);
        
   
    }//GEN-LAST:event_buttonMemoryReturnActionPerformed

    private void buttonMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryClearActionPerformed
        memoryReturn = 0;
    }//GEN-LAST:event_buttonMemoryClearActionPerformed

    private void buttonMemoryMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryMoreActionPerformed
       if (!displayScreen.getText().equals("")) {
    memoryReturn = Double.parseDouble(displayScreen.getText());
    displayScreen.setText(""+memoryReturn);
    
    }
    }//GEN-LAST:event_buttonMemoryMoreActionPerformed

    private void buttonMoreOrLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMoreOrLessActionPerformed
       if(operation != null){
           secondNumber = Double.parseDouble(displayScreen.getText());
           secondNumber = secondNumber *(-1);
           displayScreen.setText(""+secondNumber);
       }else{
       firstNumber = Double.parseDouble(displayScreen.getText());
       firstNumber = firstNumber *(-1);
       displayScreen.setText(""+firstNumber);
           
       }
    }//GEN-LAST:event_buttonMoreOrLessActionPerformed

    private void buttonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivisionActionPerformed
    if (!displayScreen.getText().equals("")) {
    firstNumber = Double.parseDouble(displayScreen.getText());
    displayScreen.setText("");
    operation = "/";
 
    }    // TODO add your handling code here:
    }//GEN-LAST:event_buttonDivisionActionPerformed

    private void buttonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiActionPerformed
    if (!displayScreen.getText().equals("")) {
    firstNumber = Double.parseDouble(displayScreen.getText());
    displayScreen.setText("");
    operation = "*";
        
     }   // TODO add your handling code here:
    }//GEN-LAST:event_buttonMultiActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
    displayScreen.setText("");
        
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
    String input ;
    input = displayScreen.getText() + buttonSeven.getText();
    displayScreen.setText(input);    

    // TODO add your handling code here:
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
    String input ;
    input = displayScreen.getText() + buttonEight.getText();
    displayScreen.setText(input);    

    // TODO add your handling code here:
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
    String input ;
    input = displayScreen.getText() + buttonNine.getText();
    displayScreen.setText(input);
        
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonNineActionPerformed

    private void buttonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLessActionPerformed
    if (!displayScreen.getText().equals("")) {
    firstNumber = Double.parseDouble(displayScreen.getText());
    displayScreen.setText("");
    operation = "-";
    } 
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonLessActionPerformed

    private void buttonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumActionPerformed
    if (!displayScreen.getText().equals("")) {
    firstNumber = Double.parseDouble(displayScreen.getText());
    displayScreen.setText("");
    operation = "+";
    }
    
    
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonSumActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
    String input;
    input = displayScreen.getText() + buttonFive.getText();
    displayScreen.setText(input);
        
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
    String input;
    input = displayScreen.getText() + buttonSix.getText();
    displayScreen.setText(input);    

    // TODO add your handling code here:
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
    String input;
    input = displayScreen.getText() + buttonFour.getText();
    displayScreen.setText(input);    

    // TODO add your handling code here:
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
    String input ;
    input = displayScreen.getText() + buttonTwo.getText();
    displayScreen.setText(input);  
        
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
    String input ;
    input = displayScreen.getText() + buttonThree.getText();
    displayScreen.setText(input);
        
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
    String input ;
    input = displayScreen.getText() + buttonOne.getText();
    displayScreen.setText(input);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOneActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
    
   
    if(operation != null){
     String resultadoFormatado;
     secondNumber = Double.parseDouble(displayScreen.getText());
        switch (operation){
            
        case "+":
            result = firstNumber + secondNumber ;
            resultadoFormatado = String.format("%.4f", result);
            displayScreen.setText(resultadoFormatado);
            memoryReturn = result;
            break;
        case "-":
            result = firstNumber - secondNumber;
            resultadoFormatado = String.format("%.4f", result);
            displayScreen.setText(resultadoFormatado);
            break;
        case "/":
            result = firstNumber / secondNumber;
            resultadoFormatado = String.format("%.2f", result);
            displayScreen.setText(resultadoFormatado);
            break;
        case "*":
            result = firstNumber * secondNumber;
            resultadoFormatado = String.format("%4.f", result);
            displayScreen.setText(resultadoFormatado);
            break;
       
    }
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void botãoZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoZeroActionPerformed
    String input ;
    input = displayScreen.getText() + botãoZero.getText();
    displayScreen.setText(input);
            
    }//GEN-LAST:event_botãoZeroActionPerformed

    private void buttomPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomPointActionPerformed
    String input ;
    input = displayScreen.getText() + buttomPoint.getText();
    displayScreen.setText(input);  
        
    // TODO add your handling code here:
    }//GEN-LAST:event_buttomPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrimCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrimCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrimCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrimCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrimCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãoZero;
    private javax.swing.JButton buttomPoint;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDivision;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonLess;
    private javax.swing.JButton buttonMemoryClear;
    private javax.swing.JButton buttonMemoryMore;
    private javax.swing.JButton buttonMemoryReturn;
    private javax.swing.JButton buttonMemoryless;
    private javax.swing.JButton buttonMoreOrLess;
    private javax.swing.JButton buttonMulti;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonSum;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JTextField displayScreen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
